# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "jpsr-iac-state"
    dynamodb_table = "my-lock-table"
    key            = "iac/jpsr/dev/./terraform.tfstate"
    region         = "us-east-2"
  }
}
